name: action test

# on: [push]
on: 
  push:
  pull_request:
    types: [closed, assigned, reopened, opened]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: list item
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
          # git clone git@github: $GITHUB_REPOSITORY
          # git checkout $GITHUB_SHA
      - name: Checks
        uses: actions/checkout@v1
      - name: list checkout files
        run: |
          pwd
          ls -a
      - name: single JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
            who-to-greet: John
      # - name: log greet time
      #   run: echo "${{ steps.greet.outputs.time }}"
