name: action test

# on: [push]
on: 
  push:
    branches:
      - master
      - 'feature/*' # matches features/a, features/b. 
      - 'feature/**' # matches features/a/b
      - '!feature/featC' # ignore featC branch
    # branches-ignore:
    #   - 'a'
    tags:
      - v1.*
    # paths:
    #   - '**.js'
    paths-ignore:
      - 'docs/**'
  

  # triggered by post request. use postman or https://tryapis.com/github/api/repos-create-dispatch-event
  repository_dispatch:
    types: [build]

  # schedule:
    # min, hour,day(month), month, day(week) check: https://crontab.guru/
    # schedule
    # - cron: "0/5 * * * *"
    # - cron: "0/6 * * * *"
    # - cron: "* * * * *"
    

  # push:
  pull_request:
    types: [closed, assigned, reopened, opened]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: payload
        run:  echo ${{ github.event.client_payload.env}}

      - name: list item
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
          # git clone git@github: $GITHUB_REPOSITORY
          # git checkout $GITHUB_SHA
      - name: Checks
        uses: actions/checkout@v1
      - name: list checkout files
        run: |
          pwd
          ls -a
      - name: single JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
            who-to-greet: John
      # - name: log greet time
      #   run: echo "${{ steps.greet.outputs.time }}"
